sudo: required

services:
- docker

env:
  global:
    - CURRENT_GIT_REF="${TRAVIS_BRANCH}" # Pass the tag, or target branch for a PR, or the branch

script:
  - make build
  - make test

before_deploy:
  # Set up git user name before generating README.md as part of deploy
  - git config --local user.name "travis-build"
  - git config --local user.email "travis@travis-ci.org"

deploy:
- provider: script
  script: make README.md deploy
  # Do not deploy if Pull Request
  # If a contributor want to deploy on its own DockerHub account:
  # 1 - Enable Travis on the forked repository
  # 2 - Set the environment variable DOCKERHUB_USERNAME in Travis Settings
  on:
    condition: $TRAVIS_PULL_REQUEST = false
