sudo: required

services:
- docker

env:
  global:
    - CURRENT_GIT_BRANCH=$TRAVIS_BRANCH

script:
- make build
- make test
- make README.md

# Do not deploy if Pull Request
# If a contributor want to deploy on its own DockerHub account:
# 1 - Enable Travis on the forked repository
# 2 - Set the environment variable DOCKERHUB_USERNAME in Travis Settings
deploy:
- provider: script
  script: make deploy
  on:
    condition: $TRAVIS_PULL_REQUEST = false
